require:
  - rubocop-rake
  - rubocop-minitest

AllCops:
  NewCops: enable
  Include:
    - 'lib/**/*.rb'
    - 'test/**/*.rb'
    - 'Rakefile'

Layout/LineLength:
  Exclude:
    - 'lib/**/*.rb'
    - 'test/**/*.rb'

Lint/NestedMethodDefinition:
  Exclude:
    - 'lib/queries/github_repository_label_active_check.rb'

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - 'lib/validators/pull_request.rb'
    - 'test/**/*.rb'

Metrics/CyclomaticComplexity:
  Max: 13

Metrics/MethodLength:
  Max: 46

Metrics/PerceivedComplexity:
  Max: 13
  Exclude:
    - 'lib/validators/pull_request.rb'

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
