AllCops:
  Include:
    - 'lib/**/*.rb'
    - 'test/**/*.rb'
    - 'Rakefile'

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/PerceivedComplexity:
  Max: 9

Metrics/LineLength:
  Exclude:
    - 'lib/**/*.rb'
    - 'test/**/*.rb'

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 25
